export const SHOP_STOCK = [
  { key: "HEAL_POTION", price: 60 },
  { key: "ANTIDOTE", price: 80 },
  { key: "EYE_DROPS", price: 80 },
  { key: "PARALYZE_CURE", price: 120 },
  { key: "WAKE_POWDER", price: 80 },
  { key: "HOLY_WATER", price: 150 },
  { key: "MANA_POTION", price: 300 },
  { key: "TOWN_PORTAL", price: 500 },
  { key: "DAGGER", price: 50 },
  { key: "WAND", price: 120 },
  { key: "SHORT_SWORD", price: 150 },
  { key: "SMALL_SHIELD", price: 80 },
  { key: "ROBE", price: 30 },
  { key: "LEATHER_ARMOR", price: 120 },
  { key: "NINJA_SUIT", price: 250 },
  { key: "AMULET_HP", price: 450 },
  { key: "AMULET_MP", price: 520 },
  { key: "RING_STR", price: 500 },
  { key: "RING_AGI", price: 480 },
  { key: "RING_LUK", price: 480 },
  { key: "THIEF_EYE", price: 520 },
  { key: "WARD_CHARM", price: 680 },
  { key: "DRAGON_RING", price: 760 },
  { key: "HOLY_BAND", price: 720 },
  { key: "SWIFT_BAND", price: 760 }
];
